#+TITLE: March 2022

* 2022-03-04

** Setting up DOOM emacs again!

*** I'm really liking it this time because I understand emacs better

** Applying for some jobs

*** I'm not actually sure if I want to take a new job.

*** I like passport a lot, but things could be better - and I could make more money...

*** Overall, I just don't quite feel like I'm reaching my full potential... and I'm not sure how to get there or what my full potential actually looks like

** WaveCX

*** I'm going to get paid soon! New macbook pro here I come!

** Rachel

*** I need to talk about our sex life with her. I just want to be able for both of us to communicate what we want...

*** I hope she'll be receptive to talking about it with me.

** Here's to hoping I can keep this diary going!!
* 2022-03-05

** Went to DOR market, it was fun!

*** Also went to old navy and did some shopping

** Watching lots of Married at First Sight and it makes me think about our relationship

*** Everything is good, but I do wish we could talk about sex more

*** I'm deciding to hold off and give Rachel a break for now.

*** I'm trying to think more about how she's feeling, and I think she is probably just tryiing to deal with her career
*** Even though I wish it wasn't so much on her mind, I think it is.

*** I told Rachel how much easier she is to love than the women on that show and I think she really appreciated it.

*** She opened up to me about how she knew she would marry me after our date of watching a romantic comedy at Zach and Catherine's

*** It was really nice to see her be vulnerable. Hopefully I can keep making her feel special and loved

* 2022-03-06

** I'm writing this from Torrington, CT! In a coffee shop called Brinx

** Rachel is helping Ms. McKeon with a dance competition and wasn't really prepared.

** She likes knowing her fate and knowing what the plan is.

** Well, time to work on some WaveCX I think.

* 2022-03-07

** WaveCX money came through! I'm currently shopping for a Macbook and headphones
* 2022-03-12
** First entry from the Macbook Air tonight!
** We went to Quaker Diner and Jene Coffee Roasters today, it was great!
** Some snow so not too fun
** Need to do some wavecx tomorrow..
* 2022-03-13
** Working on WaveCX and loving the new keyboard!
** About to play some mario party with Rachel because our internet is out.
** We cleaned today. I'm thankful that Rachel is so neat and tidy.
** I'm still trying to be patient with her on sex. I think her period is over now, so we'll see.
* 2022-03-15
** Madison emailed about click therapeutics again
** I'm definitely interested, but would feel bad about leaving passport
** I guess that's not a real reason...
** I need to make sure it's really what I want though
** We'll see what they say.
** Still waiting on Rachel... I'm trying not to get frustrated.
** Trying to be consistent in waking up early and starting work ~6am then workout / meditate around 11am and then I have more time to work in the morning and workout in the middle of the day which works better for me.
* 2022-03-16
** Interview for click therapeutics tomorrow I think
** We'll see how it goes. I'm not expecting much I suppose. I'll just be myself.
** Still waiting on Rachel... :(
** Talked to Kile today and that was nice.
** It's getting nice outside again!
* 2022-03-17
** Rachel initiated today! It was great
** We ate dinner at a mexican restraunt called Ocho cafe. It was incredible. We had chips and salsa within 10 seconds of entering the place
** Alexey said I can start working towards being an engineering manager and taking on more responsibility. I'm excited for that and feel lucky
* 2022-03-18
** I feel really good today
** Mood 😀
** Working on some WaveCX
** Rachel's performance is tomorrow!
** Interviewing with chef thing today... we'll see
* 2022-03-19
** Rache's performance was incredible!
** My favorite piece was Emily's weird yoga peice and I couldn't believe it
** So proud to see Rachel doing what she loves again
** Good to see her familiy as well. We ate at Ocho Cinco
** Met Lawson, Victoria's BF and he reminds me of Mitch from FCSA lol
* 2022-03-20
** We went to union kitchen for brunch and it was super good
** Toured some random condos after which was interesting
** Worked on wavecx and watched more Upload and MIPS (lol!) (Married in plain sight)
* 2022-03-21
** Interviewed with Demetrius from Click today
** It was great but I dont think I want to work there
** It sounds a bit disorganized and stressful with the drop dead deadlines
** Rachel initiated again today! That's twice for this period!
** I could tell she was really horny. Let's see how many more times she feels like having sex!
* 2022-03-22
** Worked a lot with event ingestion and AWS performance today
** I really enjoy learning that stuff
** Talked with Jordan Grant from Glocomm and he convinced me to keep interviewing with Chefman
** I need to really take stock of what I want and evaluate if these companies have it.
** Not just about money
** Rachel and I made some delicious chicken parm today too
* 2022-03-25
** Interview with click and chefman
** Click was good and I did a high level architecture exercise with a parking app (lol!)
** Chefman was a short coding exercise and then a react autocomplete component
*** I completed it but I'm not sure how much I like chefman as a whole...
** Click seems great, but I'm still just unsure I guess... I need to do some deep thinking about it
** Rachel and I went to Parkville Market. It's a cool food hall!
*** We had a chicken sandwich, poutine, and bubble tea!
** Rachel slipped a disk and is hurting pretty bad. I hope she feels better soon!
* 2022-03-26
** Taking care of Rachel today. I got groceries and made breakfast for us
** We watched F1 qualy in Saudi Arabia. Sergio Perez on pole!
** I made pizzas for dinner and they were fabulous!
* 2022-03-27
** Rachel isn't feeling any better today. I'm getting a bit worried. What if she can't dance anymore?
** Working on wave cx today.
** I'm feeling good about Click. Hopefully the offer is good if it comes!
* 2022-03-28
** I made delicious fajita burritos today
** Talked with Jordan Grant and Rebecca Topper today about Chefman
** I'm not really digging their salesman type vibe...
* 2022-03-29
** Talked with Madison about Click. We'll see what they come back with!
** I went to target to get a card for Dad and a treat for Rachel
** Her back is still hurting and she found out Alyssa is going to VB ballet next year
** A total slap in the face but she's taking it well. of course Alyssa would do this
** I was pissed at first, but I think it's for the best in the end to be honest
** Things are better here in Connecticut than dancing there.
* 2022-03-30
** Kile told me about VB today.
** I think I want to get some career coaching from someone who recently worked at Passport...
** I'm writing this in Southington CT while waiting for Rachel, and as of now I think I want to stay at Passport
** Even though I'm making less than I should, I think it will be better in the long term.
** I can make a name for myself at passport, blogging, etc and use that to get a better gig in the future.
** Something I'm really matched for and not just a random place I find via a recruiter
** I think I should join blogging for devs as well...
* 2022-03-31
** My Dad's birthday!
** Talked to them about that and Grandpa... he's not doing well
** Click said no
