#+TITLE: March 2022

* 2022-03-04

** Setting up DOOM emacs again!

*** I'm really liking it this time because I understand emacs better

** Applying for some jobs

*** I'm not actually sure if I want to take a new job.

*** I like passport a lot, but things could be better - and I could make more money...

*** Overall, I just don't quite feel like I'm reaching my full potential... and I'm not sure how to get there or what my full potential actually looks like

** WaveCX

*** I'm going to get paid soon! New macbook pro here I come!

** Rachel

*** I need to talk about our sex life with her. I just want to be able for both of us to communicate what we want...

*** I hope she'll be receptive to talking about it with me.

** Here's to hoping I can keep this diary going!!

* 2022-03-05

** Went to DOR market, it was fun!

*** Also went to old navy and did some shopping

** Watching lots of Married at First Sight and it makes me think about our relationship

*** Everything is good, but I do wish we could talk about sex more

*** I'm deciding to hold off and give Rachel a break for now.

*** I'm trying to think more about how she's feeling, and I think she is probably just tryiing to deal with her career

*** Even though I wish it wasn't so much on her mind, I think it is.

*** I told Rachel how much easier she is to love than the women on that show and I think she really appreciated it.

*** She opened up to me about how she knew she would marry me after our date of watching a romantic comedy at Zach and Catherine's

*** It was really nice to see her be vulnerable. Hopefully I can keep making her feel special and loved

* 2022-03-06

** I'm writing this from Torrington, CT! In a coffee shop called Brinx

** Rachel is helping Ms. McKeon with a dance competition and wasn't really prepared.

** She likes knowing her fate and knowing what the plan is.

** Well, time to work on some WaveCX I think.

* 2022-03-07

** WaveCX money came through! I'm currently shopping for a Macbook and headphones
